Update update-readme.yml

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -3,6 +3,7 @@ on:
   schedule:
     - cron: '0 * * * *' # Run every hour
   workflow_dispatch: # Allow manual trigger
+
 jobs:
   update-readme:
     runs-on: ubuntu-latest
@@ -31,7 +32,7 @@ jobs:
           fi
       
       - name: Generate README with Stats
-        if: steps.fetch-stats.outputs.stats == 'Success'
+        if: steps.fetch-stats.outputs.stats == 'Success' && steps.fetch-langs.outputs.langs == 'Success'
         run: |
           echo '<h1 align="center">' > README.md
           echo '  <a href="https://git.io/typing-svg"><img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=500&size=40&pause=1000&color=FF64DA&center=true&vCenter=true&width=435&lines=Hi%2C+I%27m+Tamanna+%F0%9F%98%8A" alt="Typing SVG" /></a>' >> README.md
@@ -49,34 +50,23 @@ jobs:
           echo '    <img height="150" align="center" alt="GitHub Stats" src="https://github-readme-stats.vercel.app/api?username=ttamanna1&include_all_commits=true&show_icons=true&theme=jolly&hide=contribs" />' >> README.md
           echo '  </a>' >> README.md
           echo '  <a href="https://github.com/ttamanna1">' >> README.md
-          echo '    <img height="150" align="center" alt="Top Languages" src="https://github-readme-stats.vercel.app/api/top-langs/?username=ttamanna1&layout=compact&title_color=ff64da&border_color=291B3E" />' >> README.md
+          echo '    <img height="150" align="center" alt="Top Languages" src="https://github-readme-stats.vercel.app/api/top-langs/?username=ttamanna1&layout=compact&title_color=ff64da&border_color=291B3E&count_private=true" />' >> README.md
           echo '  </a>' >> README.md
           echo '</div>' >> README.md
-      
-      - name: Generate README without Stats
-        if: steps.fetch-stats.outputs.stats != 'Success'
-        run: |
-          echo '<h1 align="center">' > README.md
-          echo '  <a href="https://git.io/typing-svg"><img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=500&size=40&pause=1000&color=FF64DA&center=true&vCenter=true&width=435&lines=Hi%2C+I%27m+Tamanna+%F0%9F%98%8A" alt="Typing SVG" /></a>' >> README.md
-          echo '</h1>' >> README.md
-          echo '<div align="center">' >> README.md
-          echo '  <pre>' >> README.md
-          echo '    🌱 I'"'"'m learning JavaScript and Python' >> README.md
-          echo '    💻 Bootcamp survivor and self-taught programmer' >> README.md
-          echo '    🌐 Check out my <a href="https://tamanna.dev/">website</a> ' >> README.md
-          echo '  </pre>' >> README.md
-          echo '</div>' >> README.md
-          echo '<div align="center">' >> README.md
-          echo '  <a href="https://github.com/ttamanna1">' >> README.md
-          echo '    <img height="150" align="center" alt="Top Languages" src="https://github-readme-stats.vercel.app/api/top-langs/?username=ttamanna1&layout=compact&title_color=ff64da&border_color=291B3E" />' >> README.md
-          echo '  </a>' >> README.md
-          echo '</div>' >> README.md
-      
+
       - name: Commit and Push Changes
         run: |
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
           git add README.md
           git add stats.json || true  # Add stats.json if it exists, don't fail if it doesn't
-          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with or without stats"  # Only commit if there are changes
+          git add top_languages.json || true  # Add top_languages.json if it exists, don't fail if it doesn't
+
+          # Commit changes only if there are differences
+          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest stats"
+
+          # Pull latest changes before pushing
+          git pull --rebase origin main
+
+          # Push changes to the repository
           git push
